server:
  servlet:
    context-path: /wechat
  port: 8060


spring:
  application:
    name: @artifactId@
    version: @project.version@

swagger:
  switch: true

wechat:
  app-id: test
  app-secret: test










