server:
  servlet:
    context-path: /alipaydev
  port: 9999

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

ali-pay:
  appId: 2016110200786899
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClVAB3rIj3XlcRXfDnDG7DT0EuiRJ9tCd8bCB/efPmr0JUTkg7KVC3m40j5HIqnxSNSB6IUKtHOY8iIKrC71cDuWiMrF6nUtOx/UWeYWV97i8P1WS5xnedvQ/2tOS4p1XxCBU/IDHYwpoFh+bEFw0XuY+yRJ1/wkeeoq2Ig/z2e3DfIh0MkGTJIyWyOZGEavCxcNPXytU/k6fLaPv8jwWsBrXnh6GIa36GPqb33RNtm3n3MOD69JhK+BCip0/Q+uzJVGiV0npCyg/nLkhwgOuztzUVB6y/mW2sGubCf8ni5441v8/u9LluRWI68GZ6xgPIs9KrYLK1H8yl2v8bgc7RAgMBAAECggEAYR9r9uHgxJEjTQyGzPS8zPfuLsxPlJEU8T8ECF84LTigGq6yOC8ZQAOdcoxtlSRHCohnh2T8eacSstXF+yZnU8TD6oAISvuZaWKEV3qYCNa3xvFxbsFs27mJe0DhbKjBEAvTj3X2UoRfvwgLRP7Vri5QgEVW0Qrs0AB5OU1wecstG6Yqw7GeIAuNOhTVOnlJqHuYw/XF21afL66Bj/eJ5AWVW2//hUOi9nTli9QTFoE50NxCtatj+GjNwk02XAo01CQTauNNvPJXYxXnp3hqN9SHVYHRVPtAv0fX2lTiGXFVA1u0+x9GMVwfhhBjx1DzC8KTVjgcnCJ/Zy6l/nYaUQKBgQD1OpHBth5B473/46t0dCzdUmVjt71ro3uCGuka88gKkNPb/wiD/TSLJuZ3N3zfjTr6uCn+9GQyk6MdXxB7qHSxfq4tvNHwev7Kun2AwYemM1RPAzzJguPz38mzapY60RpgllH8pQG/C++xmzxWdtIi++BuM4Z83ur/45Vqy+sPqwKBgQCslwEIr+q+Ufss2CSiAHrnLmPCeUURnj7bM49uJMbqU4JDCnqgm390JKUbL9WwyY3ljXLl18Pn1PuYXCwJKJmx9B85ceR5SdQEvwVXbu08/Rwg6oAhS/+eKqCt6peVMrTMdTbR1XNofj8hJJWmRCCZaG+2He4juObfXaqx4TxPcwKBgG7f10ztCYsi7CHJDxks+afrfBn01jjXhp0Ri7l65UQZrSA3k+MRVXNg2CyostXkZfk70QkL+E2BwOsjszElvfUOYLQfPhBrm82POfVACxPS+1hqD07Q1j3KPcjX9SqMpk9rR5BiDoMRY4M6u7IgMOxOU2+f7juBEmE1xbWukw3XAoGAGMlG+Lxq9hJIBFS2Th3LiM/8u7020iTr2gc5nhPiDV0Y5A/pNI+gakmo/JKOGemYW1NJIQEvvWe1CliSam5ORGRO560XpuOXc2cLmVbw80VWeNO0uxNzDoAIu3Fpe5/gn0xmJxSEkoku/8+FPm+iTuXUxU7fGHpBjeqhzRIP20kCgYEAgqSIiKX7SLryYfV0JmY8qh5BnAfsN3btGMHfQ88CLEnJw766LHeRlF/PFfp8SjTPy+E9vA3VC1xPxbaUZyLIK9Z0QlI4LXhl+TkLvA/aCJUMK/8j3KhtPlwi+Ia+hvIGIWCt6KRK6nsipM7PlkBHh6NvmARR80iNIe5SHGsxr7Q=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAje4oxaJniSaxcRNOC2/j5RnndkhFgEFtbgVDq0SMY2rUS3sbwZ79X9977B7ltjztIgKXAEFIb4xTk08peohPAc/laDCFhZtJvhI5d4mG/Fn0SZhndNlrOziepDAmwXWyymcarDR7orvUT5KJuWUx1es8LbexvNok0iJKmAlpkNla7+4idATIliqYizHZavnOvLWm3fJX/bo3s+EmKeHNty9Eaw9mJNlQe78wXovTstqz3wRyayKBrbGxXmYctfmMhwbs0CC4LJP/GOIVWUTO7rEPGyBPcMYdPSsuTMDX9RAAhnmyQrHHX4QPQxXI3jJ5swBUGltxnUh1ffQuPsdqCwIDAQAB
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  notifyUrl: http://j3596067n4.qicp.vip/alipaydev/aliPay/notifyUrl
  returnUrl: http://j3596067n4.qicp.vip/alipaydev/webPay/returnUrl
  timeOutExpress: 15m

