server:
  servlet:
    context-path: /alipaydev
  port: 9898

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

aliPay:
  appId: 2016110200786899
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRHHPz0ibfA6szm09Ig4kGVf2y/xGaeLFruJvgsq78aKykfv+anxyLVdVkPoitJP/UtYWijiSYz1/M6m4QCe1aiNBn71KYQCJ8IMU9ngCy9G31a+E2frtctBk8KjmTc3OBBKP3QWNoX+EQdJh73AdNptCMUUn+iWNSIIFl5GZJvtUy/U9mBAKFGcHvBcfnyYk+WT1EepK2RWQA7XYXOiY9Q4rEC6f6w1ZFRBoKoqUVvNkMXLcdSDZsN0IgZHxvHaWhXdj22O4kgRny9Uk/ALHKHSjxc42j7NAKqYjp1UsBfZhQDo6Clb+cRDqZ/GipCc/sHfXHii77WH3MfdI1/SpZAgMBAAECggEAQG405/5rjbGSsZ78CcrFkJc0SU/AO8lOWXOTS+OieRFDiJe86AZ4hBIZYv7FnBvXW9HmcBS9//t9eCUPbo+we4HGPRAHcfPo7DgorfieHIWlz8XCqcjYsBKp59jWzrD2+NzWLJwQJhvMvAZA6YD9Gxb4ERQG6Y+pc6eiVyPNxJCiaffmi3oGC0FDkpCYolWDfxNGM9ZkXw0kB8kMRpXNOMowaGE9OVrnde3GFq+fP0Sx7L6Nu7SgDPKjvSaVW4xUhvoRrS9IWtJf3zpcMXoZ2lOqB+aNJKoYRDmb34tg16mMVhXmKMkm2/bNV65rjQ4eqdyVHgGdNmudZ1LuN8f4tQKBgQDxOflFBnhVzNAk2l8YJIliezGdITvdATvy5baAukswRVYcOKFk7D7BVj3oph7hu3ulZ0L2UkhfnEtHWnlal6d6UGHixT7ou785BAEdf5QwVdNA/XwwRcqTiSt3nkMqpOggkx+cQJ8qd38hNMLrrFKorNwwOJnENn0C/PuhbQfFFwKBgQDd6vcG2BPdO9b4wUfa6xg4DBRgmIf4qjqhTsYTZqs9PBpLqUAGZjUol69QDddZBsKmoDAy/XOwz1rwPZqsXmgVV5GtNIsa+PtZsXOWthOhj7Q0JrhhrOWjVI090TPtLnHk7DSU5ASO0OYYY0M1hGVcUOau2F8dmYB+kF6cNNsSDwKBgCT+0ibu5heqkKWGRB1MxTEwWZySkz7CyLHo3wOBDrT5fUpYuQ/kV3+JPXdnusa93Smx24gxeF4Jd1YbHw9wwMO2fjysKYjB+oLBBXbDsTN0hjCqb5hrq7TSzbLLt9tbbSpJxghNtNtrdjjegaJpTEgIMsDGfXalMKj7qY/JS+7DAoGAfUU86wUguXslD8jzifW59zGCc0DHSKy3agVwtNT5BxkdcuZ4uOQLT/3IPfWCQcQaLzsv2ijOnNmAaSstW+3y7VFAb7jAaZpxMKGGMWZY0JOxUtskrCaQftGk5Wdp25KjQmnACOhqVkBAEzY9Y0F4glM81ShZEPls2oUekykXHSsCgYEAgtFvH8yrabhR2sA+PcP+xnqajWSmBpA2PhJUVkVMiD/n50WWvKiEV4xBMU9ZOaoEN9LvKIiY71pZcDxvaqJTD75IoMD/C5u9CY1GlWcjUgt1kdw1wVXlIYQNUF30JHyYF7PbQ9v8fFB9o/vnsXN887SfVWznwW5Q7TrKz/aGkvY=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAje4oxaJniSaxcRNOC2/j5RnndkhFgEFtbgVDq0SMY2rUS3sbwZ79X9977B7ltjztIgKXAEFIb4xTk08peohPAc/laDCFhZtJvhI5d4mG/Fn0SZhndNlrOziepDAmwXWyymcarDR7orvUT5KJuWUx1es8LbexvNok0iJKmAlpkNla7+4idATIliqYizHZavnOvLWm3fJX/bo3s+EmKeHNty9Eaw9mJNlQe78wXovTstqz3wRyayKBrbGxXmYctfmMhwbs0CC4LJP/GOIVWUTO7rEPGyBPcMYdPSsuTMDX9RAAhnmyQrHHX4QPQxXI3jJ5swBUGltxnUh1ffQuPsdqCwIDAQAB
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  notifyUrl: https://www.seaway.site:8079/alipaydev/aliPay/notifyUrl
  returnUrl: https://www.seaway.site:8079/alipaydev/aliPay/returnUrl

